#!/usr/bin/env bash
#comment
awk '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/) ip=$i; else if ($i ~ /^[0-9]{3}$/) code=$i} {if (ip && code) count[ip" "code]++} END {for (key in count) print count[key], key}' | sort -rn

